export const destinations = [
  {
    name: "Istanbul",
    region: "Marmara",
    lat: 41.0082,
    lng: 28.9784,
    description: "Where Europe meets Asia — iconic mosques, historic bazaars, and Bosphorus views.",
  },
  {
    name: "Cappadocia",
    region: "Central Anatolia",
    lat: 38.6431,
    lng: 34.8306,
    description: "Fairy chimneys, cave hotels, and sunrise hot air balloon rides over Mustafapaşa and Ürgüp.",
  },
  {
    name: "Antalya",
    region: "Turkish Riviera",
    lat: 36.8969,
    lng: 30.7133,
    description: "Turquoise coastline, ancient ruins, and resort towns along the Turkish Riviera.",
  },
  {
    name: "Bodrum",
    region: "Aegean",
    lat: 37.0344,
    lng: 27.4305,
    description: "Whitewashed villages, marinas, and vibrant nightlife on the Aegean coast.",
  },
  {
    name: "Foça (Izmir)",
    region: "Aegean",
    lat: 38.6667,
    lng: 26.7500,
    description: "A laid-back fishing town with Roman-era ruins and quiet coves.",
  },
  {
    name: "Bursa",
    region: "Marmara",
    lat: 40.1826,
    lng: 29.0665,
    description: "Türkiye's green city, home to the Uludağ ski resort and Ottoman-era heritage.",
  },
  {
    name: "Trabzon",
    region: "Black Sea",
    lat: 41.0027,
    lng: 39.7168,
    description: "Misty highlands and the cliffside Sümela Monastery carved into the mountainside.",
  },
  {
    name: "Gaziantep",
    region: "Southeastern Anatolia",
    lat: 37.0662,
    lng: 37.3833,
    description: "UNESCO City of Gastronomy and home to the ancient Zeugma mosaics.",
  },
  {
    name: "Halfeti",
    region: "Southeastern Anatolia",
    lat: 37.2667,
    lng: 37.8583,
    description: "The 'sunken village' — a historic town partly submerged by a dam lake.",
  },
  {
    name: "Konya",
    region: "Central Anatolia",
    lat: 37.8667,
    lng: 32.4833,
    description: "Home to the whirling dervishes and the spiritual Mevlevi Sema ceremony.",
  },
  {
    name: "Lake Van",
    region: "Eastern Anatolia",
    lat: 38.4891,
    lng: 43.4089,
    description: "Türkiye's largest lake, home to the ancient Akdamar Island church.",
  },
  {
    name: "Çanakkale",
    region: "Marmara",
    lat: 40.1553,
    lng: 26.4142,
    description: "Gateway to the ancient ruins of Troy and the historic Gallipoli peninsula.",
  },
];
