export const travelBlogPosts = [
  {
    category: 'guide',
    slug: 'turkey-student-visa-process-guide',
    title: "Turkey Student Visa Process: A Step-by-Step Guide for International Students",
    excerpt: "What to expect when applying for your student visa and residence permit to study in Türkiye.",
    body: [
      "Studying in Türkiye generally involves two separate steps: a student visa (obtained before you travel) and a residence permit, or ikamet (obtained after you arrive). Understanding both early makes the whole process far less stressful.",
      "The student visa application starts once you have an official acceptance letter from a Turkish university — this is the document Turkish consulates require before they'll process a student visa application, so it always has to come first. From there, you'll typically apply in person at the Turkish consulate or embassy nearest you, submitting your passport, acceptance letter, passport-style photos, proof of sufficient funds, and the visa application form and fee. Processing times vary by country and by consulate workload, so it's worth applying as early as your acceptance letter allows.",
      "Once you arrive in Türkiye on your student visa, you're required to apply for a residence permit within the timeframe stated on your visa — this is what allows you to legally stay for the duration of your studies, and it's a separate process from the visa itself, handled through Türkiye's immigration authority (Göç İdaresi) rather than a consulate. It typically requires your passport, visa, proof of enrollment, a Turkish address registration, and valid health insurance.",
      "Requirements and required documents can change, and they also vary somewhat by nationality and by which consulate you apply through, so treat this as a general roadmap rather than a final checklist. GoTurkey 2k2x guides students through both the visa and residence permit steps as part of our post-acceptance support — reach out once you have an offer letter and we'll walk you through exactly what's needed for your situation.",
    ],
  },
  {
    category: 'guide',
    slug: 'cost-of-living-istanbul-international-students',
    title: "Cost of Living in Istanbul for International Students",
    excerpt: "A practical breakdown of what to budget for as a student living in Istanbul.",
    body: [
      "Istanbul is often cheaper to live in than major cities in Western Europe or North America, but costs vary a lot depending on neighborhood, lifestyle, and whether you're in shared or private accommodation — so it's worth thinking in categories rather than a single number.",
      "Accommodation is usually the largest expense. Shared student apartments or dormitories are the most budget-friendly option and are common among international students, while a private studio apartment costs noticeably more, with price varying significantly by neighborhood — areas closer to major university campuses and central districts tend to run higher than residential areas further out.",
      "Day-to-day costs — groceries, public transport, and eating out at local restaurants — are generally affordable by international standards, especially if you cook regularly and use Istanbul's extensive metro, tram, and ferry network with an Istanbulkart transit card rather than relying on taxis. Mobile data plans and health insurance (required for your residence permit) are additional recurring costs worth budgeting for from day one.",
      "Because costs shift with inflation and currency exchange rates, exact figures age quickly — what matters most is planning in categories (rent, food, transport, insurance, personal spending) and building in a buffer. GoTurkey 2k2x can walk you through a realistic budget for your specific city and program once you're further along in the application process.",
    ],
  },
  {
    category: 'guide',
    slug: 'state-vs-private-universities-turkey',
    title: "State vs. Private Universities in Turkey: Which Is Right for You?",
    excerpt: "How Turkey's state and foundation (private) universities differ, and how to decide between them.",
    body: [
      "Türkiye's higher education system has two main types of universities: state universities, which are government-funded and generally follow a more traditional academic path, and foundation universities (often called \"private\" universities), which are non-profit but independently funded and run.",
      "Tuition is usually the biggest difference. State universities are typically far less expensive, sometimes minimal for certain programs, while foundation universities charge tuition that reflects their independent funding — though many also offer merit-based scholarships that reduce the effective cost significantly. In exchange, foundation universities often offer more programs taught fully in English, more modern campuses and facilities, and smaller class sizes.",
      "The application process also tends to differ. Many state university programs, especially competitive ones, require the YÖS exam (an entrance exam for international students) or equivalent standardized test scores, while most foundation universities admit based on your high school transcript and certificate alone, without a separate entrance exam — which generally means a faster, more predictable admissions timeline.",
      "Neither option is objectively \"better\" — it depends on your budget, your target program, how important English-medium instruction is to you, and how quickly you need a decision. GoTurkey 2k2x works with both state and foundation universities across Türkiye, so we can help you compare specific options for your field of study rather than choosing in the abstract.",
    ],
  },
  {
    category: 'guide',
    slug: 'document-checklist-turkish-university-application',
    title: "Document Checklist: What You Need to Apply to a Turkish University",
    excerpt: "The core documents international students need to gather before applying, in one place.",
    body: [
      "Gathering documents ahead of time is the single biggest thing you can do to keep your application moving quickly. Requirements can vary slightly by university and program, but most applications for international students in Türkiye ask for the same core set of documents.",
      "For any level of study, you'll typically need: a valid passport, a passport-style photo with a white background, your CV or resume, your high school certificate, and your high school transcript (marks/grades record). If you're applying to a Master's or Ph.D. program, you'll also need your Bachelor's degree and transcript, and Ph.D. applicants typically need their Master's degree and transcript as well.",
      "A language proficiency certificate (like IELTS or TOEFL) and a recommendation letter are commonly requested but optional for many programs — some universities run their own English-proficiency test instead of requiring an external certificate, and requirements vary by program, so it's worth confirming what's actually needed for the specific university and program you're targeting rather than assuming.",
      "Scanned copies (clear photos or PDFs) are generally sufficient to start an application, with originals sometimes required later for enrollment. This exact checklist mirrors the document upload steps in the GoTurkey 2k2x student dashboard — once you register and start an application, you'll see precisely which of these are required for your chosen program.",
    ],
  },
  {
    category: 'travel',
    slug: 'sumela-monastery-cliffs-trabzon',
    title: "Sümela Monastery: A Sacred Marvel Carved Into the Cliffs",
    excerpt: "A historic Orthodox monastery dedicated to the Virgin Mary, carved into the cliffs above Trabzon.",
    body: [
      "Clinging to a sheer cliff face nearly 1,200 meters above sea level in the Altındere Valley, Sümela Monastery is one of the most dramatic historic sites in Türkiye's Black Sea region. Founded in the late Roman period and dedicated to the Virgin Mary, the monastery grew over the centuries into a major center of Orthodox Christian pilgrimage, with monks adding chapels, kitchens, and student rooms directly into the rock itself.",
      "The centerpiece of a visit is the Rock Church, whose interior and exterior walls are covered in frescoes depicting biblical scenes, painted in layers across different centuries. Many have faded or been damaged by time and past visitors, but enough remains to give a vivid sense of the site's spiritual significance and artistic ambition.",
      "Getting there involves a scenic drive from Trabzon through pine forest and a short uphill walk to the monastery entrance — the approach alone, with the cliff face rising above the valley mist, is one of the most photographed views in the Black Sea region. Spring through early autumn is the best time to visit, when the surrounding forest is green and the mountain trails are clear.",
      "For international students settling into life in Türkiye, Trabzon and the wider Black Sea coast make for an easy weekend trip from several university cities — a reminder that studying in Türkiye also means having a UNESCO-tentative-list landmark within reach of a normal semester break.",
    ],
  },
  {
    category: 'travel',
    slug: 'lake-van-akdamar-island',
    title: "Lake Van and Akdamar Island: Lost Tales on a Sacred Isle",
    excerpt: "Exploring eastern Türkiye's dramatic natural and cultural landscape around its largest lake.",
    body: [
      "Lake Van, Türkiye's largest lake, sits high on the eastern Anatolian plateau, ringed by volcanic peaks and small fishing towns. Its alkaline waters support a unique ecosystem and give the lake a striking turquoise color that shifts with the light throughout the day.",
      "A short boat ride from the shore brings you to Akdamar Island, home to the 10th-century Cathedral of the Holy Cross. The church's exterior is carved with relief scenes from the Old Testament — Adam and Eve, David and Goliath, Jonah and the whale — remarkably well preserved reliefs that make it one of the most significant surviving examples of medieval Armenian architecture.",
      "Beyond the island, the region around Lake Van rewards slower travel: the Van Castle ruins overlooking the lake, the old town of Van with its distinctive breakfast culture, and mountain villages where daily life still follows a rhythm shaped by the surrounding highlands.",
      "Eastern Türkiye sees fewer international visitors than the coastal regions, which means sites like Akdamar Island often feel remarkably uncrowded — a genuine highlight for students looking to explore beyond the well-worn tourist trail during a semester break.",
    ],
  },
  {
    category: 'travel',
    slug: 'zeugma-mosaics-gaziantep',
    title: "Through the Eyes of the Gypsy Girl: The Hidden Story of Zeugma",
    excerpt: "The archaeological richness of Gaziantep's Roman-era mosaics and the site behind them.",
    body: [
      "Zeugma was once a major Roman city straddling the Euphrates River, founded in the 3rd century BC and known for the wealth of its merchant class. That wealth is visible today in the extraordinary mosaic floors uncovered at the site — among the finest examples of Roman mosaic art anywhere in the world.",
      "The most famous piece, known as the \"Gypsy Girl,\" depicts a woman's face with strikingly lifelike, almost photographic eyes. Its expression has made it something of an unofficial symbol for the city of Gaziantep, where the mosaic is now displayed at the Zeugma Mosaic Museum, one of the largest mosaic museums in the world.",
      "Many of the mosaics were rescued from the site before the completion of the Birecik Dam, which flooded part of the ancient city in the early 2000s — an archaeological race against time that makes the surviving collection feel even more valuable.",
      "Gaziantep itself is worth the trip on its own merits: it's widely regarded as the culinary capital of Türkiye, especially for baklava and regional kebabs, making a visit to Zeugma easy to pair with one of the country's best food scenes.",
    ],
  },
  {
    category: 'travel',
    slug: 'afyonkarahisar-gastronomy-city',
    title: "UNESCO City of Gastronomy Afyonkarahisar: Türkiye's Culinary Gem",
    excerpt: "Celebrating a region renowned for its food production and agricultural heritage.",
    body: [
      "Afyonkarahisar, in western Anatolia, holds UNESCO's Creative City of Gastronomy designation, recognizing a food culture built on centuries of local agriculture — from the region's famous clotted cream (kaymak) and sujuk sausage to its poppy-seed products and thermal-spring-fed produce.",
      "The city takes its name from the dramatic volcanic rock (kara hisar, or 'black fortress') that rises abruptly from the plain at its center, topped by the ruins of a Byzantine-era citadel with sweeping views across the surrounding countryside.",
      "Beyond the food, Afyonkarahisar is known for its thermal spas, a tradition dating back to Roman times, and for being a key site in the Turkish War of Independence — the Battle of Dumlupınar was fought nearby, and the region is dotted with memorials from that period.",
      "For visitors interested in Turkish cuisine beyond the standard tourist menu, Afyonkarahisar offers an authentic look at the regional food traditions that make up the country's much broader culinary map.",
    ],
  },
  {
    category: 'travel',
    slug: 'mevlevi-sema-ceremony-konya',
    title: "The Spiritual Rhythm of Mevlevi Sema Ceremonies",
    excerpt: "The meditative practice and ceremonial elements behind Konya's whirling dervishes.",
    body: [
      "The Sema ceremony — widely known outside Türkiye as the practice of the 'whirling dervishes' — is a form of moving meditation rooted in the teachings of the 13th-century poet and mystic Mevlana Jalaluddin Rumi, who lived and taught in Konya.",
      "Practitioners, known as semazens, spin in a slow, controlled rotation with one palm turned toward the sky and the other toward the earth, a movement said to symbolize the soul's journey toward spiritual completion while remaining connected to the material world. The ceremony follows a specific structure of music and movement, accompanied by the reed flute (ney) and devotional music.",
      "Konya, Rumi's home for much of his life, remains the center of Mevlevi culture today. The Mevlana Museum, built around his mausoleum, draws visitors from across the world, particularly around the anniversary of his death each December, marked by the Şeb-i Arus commemorations.",
      "Watching a Sema ceremony is one of the more unusual cultural experiences available to students in Türkiye — a living tradition that connects directly back to one of the most influential mystic poets in world literature.",
    ],
  },
  {
    category: 'travel',
    slug: 'kabak-bay-lycian-way',
    title: "Kabak Bay: A Hidden Paradise on the Lycian Way",
    excerpt: "A secluded cove along one of Türkiye's most famous coastal trekking routes.",
    body: [
      "Kabak Bay sits at the southern end of a long, winding descent from the village of Faralya on Türkiye's Aegean-Mediterranean coast, reachable only on foot or by a rough mountain road. That relative inaccessibility has kept it far less developed than the resorts further along the coast.",
      "The bay is a stop along the Lycian Way, a roughly 540-kilometer waymarked trekking route that follows the ancient coastline of Lycia through pine forest, cliffside paths, and small bays — widely considered one of the finest long-distance trails in the world.",
      "Kabak itself is known for eco-camps and simple beachside guesthouses rather than large hotels, drawing hikers, campers, and travelers looking for a slower, more unplugged stretch of coast. The turquoise water and steep, green hillsides make it a standout even along a coastline known for scenic bays.",
      "For students based in southwestern Türkiye, the Lycian Way offers everything from a single-day hike to a multi-week trek, with Kabak Bay as one of its most memorable and photogenic stops.",
    ],
  },
  {
    category: 'travel',
    slug: 'turkish-coffee-culture',
    title: "Turkish Coffee Culture: A Daily Ritual with Deep Cultural Roots",
    excerpt: "How this centuries-old beverage tradition shapes everyday life across Türkiye.",
    body: [
      "Turkish coffee is prepared by simmering finely ground coffee, and often sugar, together in a small pot called a cezve, producing a thick, unfiltered brew served in small cups with the grounds left to settle at the bottom. UNESCO recognized Turkish coffee culture and tradition on its Intangible Cultural Heritage list in 2013.",
      "The ritual around the coffee is as important as the drink itself. Serving Turkish coffee to guests is a long-standing gesture of hospitality, and a traditional marriage proposal custom involves the bride-to-be serving coffee to her suitor's family — sometimes swapping his cup's sugar for salt as a good-natured test of character.",
      "After finishing the cup, it's common for friends to turn the cup upside down onto its saucer and, once cooled, read the patterns left by the grounds — a lighthearted fortune-telling tradition called tasseography that remains popular across generations.",
      "For new arrivals, ordering Turkish coffee is a simple, everyday way to step into local culture — cafés across the country will happily walk first-timers through the ritual, sugar preferences and all.",
    ],
  },
  {
    category: 'travel',
    slug: 'cittaslow-towns-turkiye',
    title: "7 Cittaslow Members in Türkiye You'll Love Visiting",
    excerpt: "Charming small towns offering peaceful alternatives to Türkiye's big cities.",
    body: [
      "Cittaslow ('slow city') is an international movement, born in Italy in 1999, that certifies smaller towns committed to preserving local character, food traditions, and quality of life against the pressures of rapid urbanization. Türkiye has one of the largest numbers of Cittaslow-certified towns of any country.",
      "Towns that have earned the designation include Seferihisar, the movement's first Turkish member and an olive-growing town on the Aegean coast; Halfeti, partly submerged by a dam and known for its \"sunken\" minaret rising from the water; Şirince, a hillside village near Ephesus known for its Greek-era stone houses and fruit wines; and Taraklı, an Ottoman-era town of preserved wooden houses near Istanbul.",
      "What unites these towns is a deliberate rejection of fast-paced development: limits on chain businesses, an emphasis on local produce and artisans, and a focus on walkable, human-scale town centers. They offer a very different picture of Türkiye than its major cities — quieter, slower, and often centered on a single local specialty, from olive oil to wine to traditional crafts.",
      "For students who've settled into the pace of a big university city, a weekend in a Cittaslow town is a good way to see another side of the country: small-town Türkiye, still very much alive.",
    ],
  },
];
